name: Create GKE Cluster

on:
  push:
    branches:
      - feat/k8s  # Replace with the branch you want to trigger this workflow on

jobs:
  create_cluster:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Initialize Terraform
      run: terraform init
      working-directory: ./terraform

    - name: Apply Terraform Plan
      run: terraform apply -auto-approve
      working-directory: ./terraform

    - name: Show GKE Cluster Information
      working-directory: ./terraform
      run: |
        terraform output -json  # You can customize this based on your Terraform output
