name: Create GKE Cluster

jobs:
  create_cluster:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 4.80.0  # Replace with your desired Terraform version

    - name: Authenticate with Google Cloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Initialize Terraform
      run: terraform init
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    - name: Apply Terraform Plan
      run: terraform apply -auto-approve
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    - name: Show GKE Cluster Information
      run: |
        terraform output -json  # You can customize this based on your Terraform output
